
botmm_platform:
    apk:
        version: "|460071609915509|A6.6.9.257295"
#        version: "5.8.0.157158"
        apk_id: "com.tencent.mobileqq"
        apk_version: "6.6.9"
        sign: "A6 B7 45 BF 24 A2 C2 77 52 77 16 F6 F3 6E B6 8D" #tlv147
    android:
        imei: "864394010160994" #864394010160994
        version: "foo"
        appId: "20 02 ba 7a"
        pcVersion: "1F 41"
        osType: "android"
        osVersion: "4.4.2" #fix
        imsi: "5F 64 AA B8 ED A2 E7 73 CA 1D 79 5D E6 19 19 68" #"460071609915509" #md5(imsi)   //md5(imsi) SIM Subscriber ID
        device: "foo"
        deviceType: "MI 4LTE"
        guid: "d1 61 60 d5 b3 56 a0 a5 4f b9 93 24 a3 63 28 6b"
        deviceBrand: "Xiaomi"
        android_device_id: "90 06 af 4d 14 8c 18 22 88 1f 7e fe 8e 6d f2 39" #"A0999B095FFF0000"
        android_device_mac_hash: "d1 61 60 d5 b3 56 a0 a5 4f b9 93 24 a3 63 28 6b"

    network:
        bssid: "FA DB FA D6 6E F7 15 71 BD 7B 99 2D 9D 9C 5D B7" # //md5(bassaddr) mac md5((XX:XX:XX:XX:XX:XX).tolowercase())
        ssid: "AndroidAP" #XiaoMi WIFI
        networkType: "00 02"   #01数据网络 02wifi
        netDetail: "CMCC"
        apn: "wifi" #CMWAP #CMNET #wifi
        mac: "a3 13 8a 8d d1 7e e1 a5 84 63 d7 56 83 18 0e 87" #md5("A0:99:9B:09:5F:FF")
        client_ip: ""

#botmm_protocol:
#    tlv177: "6.3.1.1993"